### ISSUE TITLE
Retry a failed URL.

### ISSUE THREAD

**Issue by Rajendra-R** [deep-compute/gitkanban#40]
* Some times when we request a GitHub API URL we will get `Server Error` currently we are not taking any action of those urls when next run happens it will request again instead of that we have to retry of that URL.
![Screenshot 2019-03-21 at 9 31 02 AM](https://user-images.githubusercontent.com/16955073/54762650-e04b0280-4bca-11e9-949d-683cd6d62ba5.png)

**Comment by Rajendra-R** [comment]
#### status-update:
* Started working on it, as default we retry for 2 times.

**Comment by prashanthellina** [comment]
@Rajendra-R We also need to handle an API request returning failure (403) because of us hitting a rate limit as described here - https://developer.github.com/v3/#rate-limiting

<img width="702" alt="Screen Shot 2019-03-26 at 6 11 40 PM" src="https://user-images.githubusercontent.com/3989/55036997-a88cf200-4ff2-11e9-98e1-2bfd8b6f06d8.png">

If this error happens, we have to examine the timestamp in `X-RateLimit-Reset` response header and sleep till that time before making more API calls.

**Comment by Rajendra-R** [comment]
* Because of High priority work (gitkanaban prod issues, deepfetch issue) we are moving to next column. will revert back once it is done.

**Comment by Rajendra-R** [comment]
#### status-update:
* Started working on this issue today will resolve it soon.

**Comment by Rajendra-R** [comment]
* We resolved this issue so we can close this ticket.
