### ISSUE TITLE
Getting alert for pull request even if there is new commit before 24 hours

### ISSUE THREAD

**Issue by ManishaBayya** [deep-compute/gitkanban#46]
Reference: https://github.com/deep-compute/kwikui/pull/700
![image](https://user-images.githubusercontent.com/34316267/54823786-e32f1b80-4cce-11e9-987c-64f71e2257f1.png)

In the above pull req @jaswanth098 suggested some changes and @chatrapathik gave commit fixing those changes but still it shows alert.

**Comment by Rajendra-R** [comment]
@ManishaBayya 
* Currently we are treating issues and pull requests are same for now, and we are considering only issue comment messages, we already tracking this issue separately at https://github.com/deep-compute/gitkanban/issues/33 so, will be resolving this problem soon.
* Because of the duplicate issue we are closing this.
